# code: language=ansible
---
- name: Install the correct etckeeper
  ansible.builtin.include_tasks: "{{ ansible_facts['os_family'] | lower }}.yml"

- name: Check etckeeper initiated
  ansible.builtin.stat:
    path: /etc/.git
  register: etckeeper_init

- name: Etckeeper initial
  ansible.builtin.command:
    etckeeper init
  when: not etckeeper_init.stat.exists
  register: run_etckeeper_init
  changed_when: run_etckeeper_init.rc == 0

- name: Add cron job to generate list of packages
  ansible.builtin.cron:
    name: "list of packages"
    job: "/usr/bin/rpm -qa | sort > /etc/packages.txt 2>/dev/null"
    special_time: daily
